In [117]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import preprocessing

## Salary data (TEST)

In [118]:
salarytest=pd.read_csv('SalaryData_Test(1).csv')
salarytest

age      workclass      education  educationno        maritalstatus  \
0       25        Private           11th            7        Never-married   
1       38        Private        HS-grad            9   Married-civ-spouse   
2       28      Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44        Private   Some-college           10   Married-civ-spouse   
4       34        Private           10th            6        Never-married   
...    ...            ...            ...          ...                  ...   
15055   33        Private      Bachelors           13        Never-married   
15056   39        Private      Bachelors           13             Divorced   
15057   38        Private      Bachelors           13   Married-civ-spouse   
15058   44        Private      Bachelors           13             Divorced   
15059   35   Self-emp-inc      Bachelors           13   Married-civ-spouse   

               occupation    relationship                 race      sex  \
0       Machine-op-inspct       Own-child                Black     Male   
1         Farming-fishing         Husband                White     Male   
2         Protective-serv         Husband                White     Male   
3       Machine-op-inspct         Husband                Black     Male   
4           Other-service   Not-in-family                White     Male   
...                   ...             ...                  ...      ...   
15055      Prof-specialty       Own-child                White     Male   
15056      Prof-specialty   Not-in-family                White   Female   
15057      Prof-specialty         Husband                White     Male   
15058        Adm-clerical       Own-child   Asian-Pac-Islander     Male   
15059     Exec-managerial         Husband                White     Male   

       capitalgain  capitalloss  hoursperweek          native  Salary  
0                0            0            40   United-States   <=50K  
1                0            0            50   United-States   <=50K  
2                0            0            40   United-States    >50K  
3             7688            0            40   United-States    >50K  
4                0            0            30   United-States   <=50K  
...            ...          ...           ...             ...     ...  
15055            0            0            40   United-States   <=50K  
15056            0            0            36   United-States   <=50K  
15057            0            0            50   United-States   <=50K  
15058         5455            0            40   United-States   <=50K  
15059            0            0            60   United-States    >50K  

[15060 rows x 14 columns]

In [119]:
salarytest.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  15060.000000  15060.000000  15060.000000  15060.000000  15060.000000
mean      38.768327     10.112749   1120.301594     89.041899     40.951594
std       13.380676      2.558727   7703.181842    406.283245     12.062831
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       48.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   3770.000000     99.000000

In [120]:
salarytest.head()

age   workclass      education  educationno        maritalstatus  \
0   25     Private           11th            7        Never-married   
1   38     Private        HS-grad            9   Married-civ-spouse   
2   28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3   44     Private   Some-college           10   Married-civ-spouse   
4   34     Private           10th            6        Never-married   

           occupation    relationship    race    sex  capitalgain  \
0   Machine-op-inspct       Own-child   Black   Male            0   
1     Farming-fishing         Husband   White   Male            0   
2     Protective-serv         Husband   White   Male            0   
3   Machine-op-inspct         Husband   Black   Male         7688   
4       Other-service   Not-in-family   White   Male            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            50   United-States   <=50K  
2            0            40   United-States    >50K  
3            0            40   United-States    >50K  
4            0            30   United-States   <=50K

#### Complete salarytest dataset

In [121]:
label_encoder=preprocessing.LabelEncoder()
salarytest['Salary']=label_encoder.fit_transform(salarytest['Salary'])

In [122]:
salarytest.Salary

0        0
1        0
2        1
3        1
4        0
        ..
15055    0
15056    0
15057    0
15058    0
15059    1
Name: Salary, Length: 15060, dtype: int32

In [123]:
salarytest['workclass']= label_encoder.fit_transform(salarytest['workclass'])
salarytest['education']= label_encoder.fit_transform(salarytest['education'])
salarytest['maritalstatus']= label_encoder.fit_transform(salarytest['maritalstatus'])
salarytest['occupation']= label_encoder.fit_transform(salarytest['occupation'])
salarytest['relationship'] = label_encoder.fit_transform(salarytest['relationship'])
salarytest['sex']= label_encoder.fit_transform(salarytest['sex'])
salarytest['native']= label_encoder.fit_transform(salarytest['native'])
salarytest['race']= label_encoder.fit_transform(salarytest['race'])

In [124]:
salarytest

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            40   
15056             1     4    0            0            0            36   
15057             0     4    1            0            0            50   
15058             3     1    1         5455            0            40   
15059             0     4    1            0            0            60   

       native  Salary  
0          37       0  
1          37       0  
2          37       1  
3          37       1  
4          37       0  
...       ...     ...  
15055      37       0  
15056      37       0  
15057      37       0  
15058      37       0  
15059      37       1  

[15060 rows x 14 columns]

In [125]:
salarytest.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [126]:
# salary test data
x=salarytest.iloc[:,0:13]    # x & y test data
y=salarytest['Salary'] 

In [127]:
x

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   33          2          9           13              4           9   
15056   39          2          9           13              0           9   
15057   38          2          9           13              2           9   
15058   44          2          9           13              0           0   
15059   35          3          9           13              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 3     2    1            0            0            40      37  
1                 0     4    1            0            0            50      37  
2                 0     4    1            0            0            40      37  
3                 0     2    1         7688            0            40      37  
4                 1     4    1            0            0            30      37  
...             ...   ...  ...          ...          ...           ...     ...  
15055             3     4    1            0            0            40      37  
15056             1     4    0            0            0            36      37  
15057             0     4    1            0            0            50      37  
15058             3     1    1         5455            0            40      37  
15059             0     4    1            0            0            60      37  

[15060 rows x 13 columns]

In [128]:
y

0        0
1        0
2        1
3        1
4        0
        ..
15055    0
15056    0
15057    0
15058    0
15059    1
Name: Salary, Length: 15060, dtype: int32

In [129]:
salarytest.Salary.unique()

array([0, 1])

In [130]:
salarytest.Salary.value_counts()

0    11360
1     3700
Name: Salary, dtype: int64

In [131]:
# Splitting the data into training and test dataset

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [132]:
#model building by using SVM
clf=SVC()
clf.fit(x_train , y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 79.6812749003984


array([[3290,   95],
       [ 823,  310]], dtype=int64)

In [133]:
y_pred=clf.predict(x_test)

In [134]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

## Salary data (TRAIN)

In [135]:
salarytrain=pd.read_csv('SalaryData_Train(1).csv.crdownload')
salarytrain

age          workclass      education  educationno  \
0       39          State-gov      Bachelors           13   
1       50   Self-emp-not-inc      Bachelors           13   
2       38            Private        HS-grad            9   
3       53            Private           11th            7   
4       28            Private      Bachelors           13   
...    ...                ...            ...          ...   
13247   26            Private   Some-college           10   
13248   22            Private           10th            6   
13249   25            Private        Masters           14   
13250   28            Private   Some-college           10   
13251   41            Private     Assoc-acdm           12   

             maritalstatus          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
13247   Married-civ-spouse     Exec-managerial            Wife   White   
13248        Never-married               Sales   Not-in-family   White   
13249        Never-married        Adm-clerical       Own-child   White   
13250   Married-civ-spouse        Adm-clerical            Wife   White   
13251             Divorced        Adm-clerical             NaN     NaN   

           sex  capitalgain  capitalloss  hoursperweek          native  Salary  
0         Male       2174.0          0.0          40.0   United-States   <=50K  
1         Male          0.0          0.0          13.0   United-States   <=50K  
2         Male          0.0          0.0          40.0   United-States   <=50K  
3         Male          0.0          0.0          40.0   United-States   <=50K  
4       Female          0.0          0.0          40.0            Cuba   <=50K  
...        ...          ...          ...           ...             ...     ...  
13247   Female          0.0          0.0          25.0   United-States   <=50K  
13248   Female          0.0       1762.0          25.0   United-States   <=50K  
13249     Male          0.0          0.0          40.0   United-States   <=50K  
13250   Female          0.0          0.0          15.0   United-States   <=50K  
13251      NaN          NaN          NaN           NaN             NaN     NaN  

[13252 rows x 14 columns]

In [136]:
salarytrain.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  13252.000000  13252.000000  13251.000000  13251.000000  13251.000000
mean      38.413975     10.122698   1077.236435     89.355898     40.976002
std       13.122588      2.529555   7390.862975    404.346942     11.867362
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   3770.000000     99.000000

In [137]:
salarytrain.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male       2174.0   
1     Exec-managerial         Husband   White     Male          0.0   
2   Handlers-cleaners   Not-in-family   White     Male          0.0   
3   Handlers-cleaners         Husband   Black     Male          0.0   
4      Prof-specialty            Wife   Black   Female          0.0   

   capitalloss  hoursperweek          native  Salary  
0          0.0          40.0   United-States   <=50K  
1          0.0          13.0   United-States   <=50K  
2          0.0          40.0   United-States   <=50K  
3          0.0          40.0   United-States   <=50K  
4          0.0          40.0            Cuba   <=50K

#### Complete  salarytrain dataset

In [138]:
label_encoder=preprocessing.LabelEncoder()
salarytrain['Salary']=label_encoder.fit_transform(salarytrain['Salary'])

In [139]:
salarytrain.Salary

0        0
1        0
2        0
3        0
4        0
        ..
13247    0
13248    0
13249    0
13250    0
13251    2
Name: Salary, Length: 13252, dtype: int32

In [140]:
salarytrain['workclass']= label_encoder.fit_transform(salarytrain['workclass'])
salarytrain['education']= label_encoder.fit_transform(salarytrain['education'])
salarytrain['maritalstatus']= label_encoder.fit_transform(salarytrain['maritalstatus'])
salarytrain['occupation']= label_encoder.fit_transform(salarytrain['occupation'])
salarytrain['relationship'] = label_encoder.fit_transform(salarytrain['relationship'])
salarytrain['sex']= label_encoder.fit_transform(salarytrain['sex'])
salarytrain['native']= label_encoder.fit_transform(salarytrain['native'])
salarytrain['race']= label_encoder.fit_transform(salarytrain['race'])

In [141]:
salarytrain

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
13247   26          2         15           10              2           3   
13248   22          2          0            6              4          11   
13249   25          2         12           14              4           0   
13250   28          2         15           10              2           0   
13251   41          2          7           12              0           0   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1       2174.0          0.0          40.0   
1                 0     4    1          0.0          0.0          13.0   
2                 1     4    1          0.0          0.0          40.0   
3                 0     2    1          0.0          0.0          40.0   
4                 5     2    0          0.0          0.0          40.0   
...             ...   ...  ...          ...          ...           ...   
13247             5     4    0          0.0          0.0          25.0   
13248             1     4    0          0.0       1762.0          25.0   
13249             3     4    1          0.0          0.0          40.0   
13250             5     4    0          0.0          0.0          15.0   
13251             6     5    2          NaN          NaN           NaN   

       native  Salary  
0          37       0  
1          37       0  
2          37       0  
3          37       0  
4           4       0  
...       ...     ...  
13247      37       0  
13248      37       0  
13249      37       0  
13250      37       0  
13251      40       2  

[13252 rows x 14 columns]

In [142]:
salarytrain.isna().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      1
capitalloss      1
hoursperweek     1
native           0
Salary           0
dtype: int64

In [143]:
# salary train  data
X=salarytrain.iloc[:,0:13]  # X & Y train data
Y=salarytrain['Salary'] 

In [144]:
X

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
13247   26          2         15           10              2           3   
13248   22          2          0            6              4          11   
13249   25          2         12           14              4           0   
13250   28          2         15           10              2           0   
13251   41          2          7           12              0           0   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 1     4    1       2174.0          0.0          40.0      37  
1                 0     4    1          0.0          0.0          13.0      37  
2                 1     4    1          0.0          0.0          40.0      37  
3                 0     2    1          0.0          0.0          40.0      37  
4                 5     2    0          0.0          0.0          40.0       4  
...             ...   ...  ...          ...          ...           ...     ...  
13247             5     4    0          0.0          0.0          25.0      37  
13248             1     4    0          0.0       1762.0          25.0      37  
13249             3     4    1          0.0          0.0          40.0      37  
13250             5     4    0          0.0          0.0          15.0      37  
13251             6     5    2          NaN          NaN           NaN      40  

[13252 rows x 13 columns]

In [145]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
13247    0
13248    0
13249    0
13250    0
13251    2
Name: Salary, Length: 13252, dtype: int32

In [146]:
salarytrain.Salary.unique()

array([0, 1, 2])

In [147]:
salarytrain.Salary.value_counts()

0    9991
1    3260
2       1
Name: Salary, dtype: int64

In [148]:
# Splitting the data into training and test dataset

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=0)

In [149]:
clf=SVC()
clf.fit(x_train ,y_train)
y_pred = clf.predict(x_train)
acc = accuracy_score(y_train, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_train, y_pred)

Accuracy = 79.6895213454075


array([[6767,  218],
       [1666,  625]], dtype=int64)

In [150]:
y_pred=clf.predict(x_train)

In [151]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])